// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBnqbJZJwD8ksA-KcMewCSzUEIYRLq4aE',
    appId: '1:194907002616:web:434c81bd18e5032ac9cd0d',
    messagingSenderId: '194907002616',
    projectId: 'clan-track-cbb88',
    authDomain: 'clan-track-cbb88.firebaseapp.com',
    storageBucket: 'clan-track-cbb88.appspot.com',
    measurementId: 'G-EBV4DS56FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-VnRHlrSA4s22yrCE_np5NiBL9WYBSk',
    appId: '1:194907002616:android:7ff4edf6faf05e26c9cd0d',
    messagingSenderId: '194907002616',
    projectId: 'clan-track-cbb88',
    storageBucket: 'clan-track-cbb88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdcJTCebyIXu_vN5J5-NElk-8fAr-WMs',
    appId: '1:194907002616:ios:5b48544e875a635ac9cd0d',
    messagingSenderId: '194907002616',
    projectId: 'clan-track-cbb88',
    storageBucket: 'clan-track-cbb88.appspot.com',
    iosBundleId: 'com.example.clanTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgdcJTCebyIXu_vN5J5-NElk-8fAr-WMs',
    appId: '1:194907002616:ios:da40d83bfc99168bc9cd0d',
    messagingSenderId: '194907002616',
    projectId: 'clan-track-cbb88',
    storageBucket: 'clan-track-cbb88.appspot.com',
    iosBundleId: 'com.example.clanTrack.RunnerTests',
  );
}
